spring:
  servlet:
    multipart:
      max-file-size=40MB
      max-request-size=40MB

server:
  error:
    include-message: always

updateYtdl: false

directory:
  audio: E:\Adri\Music
  playlist: E:\Adri\Music\Playlists
